<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-840BIJ2" failures="1" tests="1" name="Test2_validuname_invalidpwd" time="65.636" errors="0" timestamp="2023-12-10T16:32:59 IST">
  <testcase classname="topic_ITest.TestresContext2" name="sdLogin" time="18.91">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at topic_ITest.TestresContext2.sdLogin(TestresContext2.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sdLogin -->
</testsuite> <!-- Test2_validuname_invalidpwd -->
